quarkus.banner.enabled=true
#quarkus.http.host=0.0.0.0
quarkus.http.port=9090

quarkus.locales=fr-FR
quarkus.default-locale=fr-FR

# En production, Quarkus doit savoir qu'il est derrière un proxy (pour les headers)
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-host=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.schema-management.strategy=drop-and-create
#quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.log.level=INFO
%dev.quarkus.log.category."org.jluc.ctr.tools.calendrier.server".level=DEBUG
%dev.quarkus.log.category."org.jluc.ctr.tools.calendrier.server.resource".level=DEBUG
%dev.quarkus.log.category."org.hibernate".level=INFO
# log pour le mailer
%dev.quarkus.log.category."org.jluc.ctr.tools.calendrier.server.service.mail".level=INFO
%dev.quarkus.log.category."io.quarkus.mailer".level=INFO
%dev.quarkus.log.category."org.jboss.resteasy".level=DEBUG
%dev.quarkus.log.category."org.jboss.logmanager".level=INFO
# log pour smtp
%dev.quarkus.log.category."org.simplejavamail".level=INFO

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
#quarkus.hibernate-orm.log.sql=true

# Configuration du serveur SMTP (exemple pour Gmail)
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${MAIL_USERNAME}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${MAIL_USERNAME}
quarkus.mailer.password=${MAIL_PASSWORD}
#quarkus.mailer.tls=true
quarkus.mailer.mock=false

# Definition des users et roles pour la securite.
quarkus.security.users.file.enabled=true
quarkus.security.users.file.plain-text=true
quarkus.security.users.file.users=users.properties
quarkus.security.users.file.roles=roles.properties
# quarkus.security.users.file.realm-name=CTR-Planning
quarkus.security.jaxrs.deny-unannotated-endpoints=true

# Clé secrète pour signer les JWT (à générer via `openssl rand -base64 32`)
# smallrye.jwt.sign.key=GPaL4jyU0biGecFzdraNKnJReWuN6z9Xl2Z8iF4bjH4=

# === PROFIL DEV ===
# %dev.quarkus.log.category."io.quarkus.security".level=DEBUG
%dev.mp.jwt.verify.publickey.location=publicKey.pem
%dev.smallrye.jwt.sign.key.location=privateKey.pem
%dev.mp.jwt.verify.issuer=http://localhost

%dev.quarkus.security.users.file.enabled=true
%dev.quarkus.security.users.file.plain-text=true
%dev.quarkus.security.users.file.users=users.properties
%dev.quarkus.security.users.file.roles=roles.properties
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=calendrier_ctr_app
%dev.quarkus.datasource.password=Cal3ndr13rCTR!*
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/calendrier_ctr_bdd

# === PROFIL PROD ===
mp.jwt.verify.publickey.location=/etc/secrets/publicKey.pem
smallrye.jwt.sign.key.location=/etc/secrets/privateKey.pem
mp.jwt.verify.issuer=https://ctr.blondy29.ovh