ctr=Admin,admin,ctr,user
ctd_22=ctd,user
ctd_29=ctd,user
ctd_35=ctd,user
ctd_44=ctd,user
ctd_49=ctd,user
ctd_53=ctd,user
ctd_56=ctd,user
ctd_72=ctd,user
ctd_85=ctd,user
cap=sca,user
assub_paimpol=sca,user
camaret=sca,user
cip_glenans=sca,user
du_cote_de_roussay=sca,user
maitai=sca,user
subevasion=sca,user
jluc=Admin,admin,ctr,user
